version: '3'

networks:
  personniNetwork:
    driver: bridge

services:
  personniMoveisDB:
    image: postgres
    container_name: personniMoveisDB
    restart: always
    networks: 
      - personniNetwork
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  spring_api:
    build: "."
    container_name: spring_api
    depends_on: 
      - personniMoveisDB
    networks:
      - personniNetwork
    environment:
      - PORT=8081
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_NAME}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8081:8081"
      - "8888:8888"